use nba_stats_raw;

CREATE TABLE IF NOT EXISTS advanced (
seas_id INT,
season INT,
player_id INT,
player VARCHAR(255),
pos VARCHAR(8),
age FLOAT,
experience INT,
lg VARCHAR(10),
tm VARCHAR(3),
g INT,
mp FLOAT,
per FLOAT,
ts_percent FLOAT,
x3p_ar FLOAT,
f_tr FLOAT,
orb_percent FLOAT,
drb_percent FLOAT,
trb_percent FLOAT,
ast_percent FLOAT,
stl_percent FLOAT,
blk_percent FLOAT,
tov_percent FLOAT,
usg_percent FLOAT,
ows FLOAT,
dws FLOAT,
ws FLOAT,
ws_48 FLOAT,
obpm FLOAT,
dbpm FLOAT,
bpm FLOAT,
vorp FLOAT
);

CREATE TABLE IF NOT EXISTS all_star_selections (
player VARCHAR(255),
team VARCHAR(50),
lg VARCHAR(10),
season INT,
replaced TINYINT
);

CREATE TABLE IF NOT EXISTS end_of_season_teams_voting (
season INT,
lg VARCHAR(10),
`type` VARCHAR(50),
number_tm VARCHAR(3),
position VARCHAR(8),
player VARCHAR(255),
age INT,
tm VARCHAR(3),
pts_won FLOAT,
pts_max FLOAT,
`share` DECIMAL(5,4),
x1st_tm FLOAT,
x2nd_tm FLOAT,
x3rd_tm FLOAT,
seas_id INT,
player_id INT
);

CREATE TABLE IF NOT EXISTS end_of_season_teams (
season INT,
lg VARCHAR(10),
`type` VARCHAR(50),
number_tm VARCHAR(3),
player VARCHAR(255),
position VARCHAR(8),
seas_id INT,
player_id INT,
tm VARCHAR(3),
age INT
);

CREATE TABLE IF NOT EXISTS opponent_stats_per_100_poss (
season INT,
lg VARCHAR(10),
team VARCHAR(50),
abbreviation VARCHAR(255),
playoffs TINYINT,
g INT,
mp INT,
opp_fg_per_100_poss FLOAT,
opp_fga_per_100_poss FLOAT,
opp_fg_percent FLOAT,
opp_x3p_per_100_poss FLOAT,
opp_x3pa_per_100_poss FLOAT,
opp_x3p_percent FLOAT,
opp_x2p_per_100_poss FLOAT,
opp_x2pa_per_100_poss FLOAT,
opp_x2p_percent FLOAT,
opp_ft_per_100_poss FLOAT,
opp_fta_per_100_poss FLOAT,
opp_ft_percent FLOAT,
opp_orb_per_100_poss FLOAT,
opp_drb_per_100_poss FLOAT,
opp_trb_per_100_poss FLOAT,
opp_ast_per_100_poss FLOAT,
opp_stl_per_100_poss FLOAT,
opp_blk_per_100_poss FLOAT,
opp_tov_per_100_poss FLOAT,
opp_pf_per_100_poss FLOAT,
opp_pts_per_100_poss FLOAT
);

CREATE TABLE IF NOT EXISTS opponent_stats_per_game (
season INT,
lg VARCHAR(10),
team VARCHAR(50),
abbreviation VARCHAR(255),
playoffs TINYINT,
g FLOAT,
mp_per_game FLOAT,
opp_fg_per_game FLOAT,
opp_fga_per_game FLOAT,
opp_fg_percent FLOAT,
opp_x3p_per_game FLOAT,
opp_x3pa_per_game FLOAT,
opp_x3p_percent FLOAT,
opp_x2p_per_game FLOAT,
opp_x2pa_per_game FLOAT,
opp_x2p_percent FLOAT,
opp_ft_per_game FLOAT,
opp_fta_per_game FLOAT,
opp_ft_percent FLOAT,
opp_orb_per_game FLOAT,
opp_drb_per_game FLOAT,
opp_trb_per_game FLOAT,
opp_ast_per_game FLOAT,
opp_stl_per_game FLOAT,
opp_blk_per_game FLOAT,
opp_tov_per_game FLOAT,
opp_pf_per_game FLOAT,
opp_pts_per_game FLOAT
);

CREATE TABLE IF NOT EXISTS opponent_totals (
season INT,
lg VARCHAR(10),
team VARCHAR(50),
abbreviation VARCHAR(3),
playoffs TINYINT,
g FLOAT,
mp FLOAT,
opp_fg FLOAT,
opp_fga FLOAT,
opp_fg_percent FLOAT,
opp_x3p FLOAT,
opp_x3pa FLOAT,
opp_x3p_percent FLOAT,
opp_x2p FLOAT,
opp_x2pa FLOAT,
opp_x2p_percent FLOAT,
opp_ft FLOAT,
opp_fta FLOAT,
opp_ft_percent FLOAT,
opp_orb FLOAT,
opp_drb FLOAT,
opp_trb FLOAT,
opp_ast FLOAT,
opp_stl FLOAT,
opp_blk FLOAT,
opp_tov FLOAT,
opp_pf FLOAT,
opp_pts FLOAT
);

CREATE TABLE IF NOT EXISTS per_100_poss (
seas_id INT,
season INT,
player_id INT,
player VARCHAR(255),
pos VARCHAR(8),
age INT,
experience INT,
lg VARCHAR(10),
tm VARCHAR(3),
g INT,
gs FLOAT,
mp INT,
fg_per_100_poss FLOAT,
fga_per_100_poss FLOAT,
fg_percent FLOAT,
x3p_per_100_poss FLOAT,
x3pa_per_100_poss FLOAT,
x3p_percent FLOAT,
x2p_per_100_poss FLOAT,
x2pa_per_100_poss FLOAT,
x2p_percent FLOAT,
ft_per_100_poss FLOAT,
fta_per_100_poss FLOAT,
ft_percent FLOAT,
orb_per_100_poss FLOAT,
drb_per_100_poss FLOAT,
trb_per_100_poss FLOAT,
ast_per_100_poss FLOAT,
stl_per_100_poss FLOAT,
blk_per_100_poss FLOAT,
tov_per_100_poss FLOAT,
pf_per_100_poss FLOAT,
pts_per_100_poss FLOAT,
o_rtg FLOAT,
d_rtg FLOAT
);

CREATE TABLE IF NOT EXISTS per_36_minutes (
seas_id INT,
season INT,
player_id INT,
player VARCHAR(255),
pos VARCHAR(8),
age FLOAT,
experience INT,
lg VARCHAR(10),
tm VARCHAR(3),
g INT,
gs FLOAT,
mp FLOAT,
fg_per_36_min FLOAT,
fga_per_36_min FLOAT,
fg_percent FLOAT,
x3p_per_36_min FLOAT,
x3pa_per_36_min FLOAT,
x3p_percent FLOAT,
x2p_per_36_min FLOAT,
x2pa_per_36_min FLOAT,
x2p_percent FLOAT,
ft_per_36_min FLOAT,
fta_per_36_min FLOAT,
ft_percent FLOAT,
orb_per_36_min FLOAT,
drb_per_36_min FLOAT,
trb_per_36_min FLOAT,
ast_per_36_min FLOAT,
stl_per_36_min FLOAT,
blk_per_36_min FLOAT,
tov_per_36_min FLOAT,
pf_per_36_min FLOAT,
pts_per_36_min FLOAT
);

CREATE TABLE IF NOT EXISTS player_award_shares (
season INT,
award VARCHAR(20),
player VARCHAR(255),
age INT,
tm VARCHAR(3),
`first` FLOAT,
pts_won FLOAT,
pts_max FLOAT,
`share` FLOAT,
winner TINYINT,
seas_id INT,
player_id INT
);

CREATE TABLE IF NOT EXISTS player_career_info (
player_id INT,
player VARCHAR(255),
hof TINYINT,
num_seasons INT,
first_seas INT,
last_seas INT,
pos VARCHAR(8),
ht_in_in INT,
wt FLOAT,
birth_date VARCHAR(10),
colleges VARCHAR(255),
slug VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS player_per_game (
seas_id INT,
season INT,
player_id INT,
player VARCHAR(255),
pos VARCHAR(8),
age FLOAT,
experience INT,
lg VARCHAR(10),
tm VARCHAR(3),
g INT,
gs FLOAT,
mp_per_game FLOAT,
fg_per_game FLOAT,
fga_per_game FLOAT,
fg_percent FLOAT,
x3p_per_game FLOAT,
x3pa_per_game FLOAT,
x3p_percent FLOAT,
x2p_per_game FLOAT,
x2pa_per_game FLOAT,
x2p_percent FLOAT,
e_fg_percent FLOAT,
ft_per_game FLOAT,
fta_per_game FLOAT,
ft_percent FLOAT,
orb_per_game FLOAT,
drb_per_game FLOAT,
trb_per_game FLOAT,
ast_per_game FLOAT,
stl_per_game FLOAT,
blk_per_game FLOAT,
tov_per_game FLOAT,
pf_per_game FLOAT,
pts_per_game FLOAT
);

CREATE TABLE IF NOT EXISTS player_play_by_play (
seas_id FLOAT,
season INT,
player_id FLOAT,
player VARCHAR(255),
pos VARCHAR(8),
age INT,
experience FLOAT,
lg VARCHAR(10),
tm VARCHAR(3),
g INT,
mp INT,
pg_percent FLOAT,
sg_percent FLOAT,
sf_percent FLOAT,
pf_percent FLOAT,
c_percent FLOAT,
on_court_plus_minus_per_100_poss FLOAT,
net_plus_minus_per_100_poss FLOAT,
bad_pass_turnover INT,
lost_ball_turnover INT,
shooting_foul_committed INT,
offensive_foul_committed INT,
shooting_foul_drawn INT,
offensive_foul_drawn FLOAT,
points_generated_by_assists INT,
and1 INT,
fga_blocked INT
);

CREATE TABLE IF NOT EXISTS player_season_info (
season INT,
seas_id INT,
player_id INT,
player VARCHAR(255),
pos VARCHAR(8),
age FLOAT,
lg VARCHAR(10),
tm VARCHAR(3),
experience INT
);

CREATE TABLE IF NOT EXISTS player_shooting (
seas_id INT,
season INT,
player_id INT,
player VARCHAR(255),
pos VARCHAR(8),
age INT,
experience INT,
lg VARCHAR(10),
tm VARCHAR(3),
g INT,
mp INT,
fg_percent FLOAT,
avg_dist_fga FLOAT,
percent_fga_from_x2p_range FLOAT,
percent_fga_from_x0_3_range FLOAT,
percent_fga_from_x3_10_range FLOAT,
percent_fga_from_x10_16_range FLOAT,
percent_fga_from_x16_3p_range FLOAT,
percent_fga_from_x3p_range FLOAT,
fg_percent_from_x2p_range FLOAT,
fg_percent_from_x0_3_range FLOAT,
fg_percent_from_x3_10_range FLOAT,
fg_percent_from_x10_16_range FLOAT,
fg_percent_from_x16_3p_range FLOAT,
fg_percent_from_x3p_range FLOAT,
percent_assisted_x2p_fg FLOAT,
percent_assisted_x3p_fg FLOAT,
percent_dunks_of_fga FLOAT,
num_of_dunks INT,
percent_corner_3s_of_3pa FLOAT,
corner_3_point_percent FLOAT,
num_heaves_attempted INT,
num_heaves_made INT
);

CREATE TABLE IF NOT EXISTS player_totals (
seas_id INT,
season INT,
player_id INT,
player VARCHAR(255),
pos VARCHAR(8),
age FLOAT,
experience INT,
lg VARCHAR(10),
tm VARCHAR(3),
g INT,
gs FLOAT,
mp FLOAT,
fg INT,
fga INT,
fg_percent FLOAT,
x3p FLOAT,
x3pa FLOAT,
x3p_percent FLOAT,
x2p INT,
x2pa INT,
x2p_percent FLOAT,
e_fg_percent FLOAT,
ft INT,
fta INT,
ft_percent FLOAT,
orb FLOAT,
drb FLOAT,
trb FLOAT,
ast INT,
stl FLOAT,
blk FLOAT,
tov FLOAT,
pf INT,
pts INT
);

CREATE TABLE IF NOT EXISTS team_abbrev (
season INT,
lg VARCHAR(10),
team VARCHAR(50),
playoffs TINYINT,
abbreviation VARCHAR(3)
);

CREATE TABLE IF NOT EXISTS team_stats_per_100_poss (
season INT,
lg VARCHAR(10),
team VARCHAR(50),
abbreviation VARCHAR(3),
playoffs TINYINT,
g INT,
mp INT,
fg_per_100_poss FLOAT,
fga_per_100_poss FLOAT,
fg_percent FLOAT,
x3p_per_100_poss FLOAT,
x3pa_per_100_poss FLOAT,
x3p_percent FLOAT,
x2p_per_100_poss FLOAT,
x2pa_per_100_poss FLOAT,
x2p_percent FLOAT,
ft_per_100_poss FLOAT,
fta_per_100_poss FLOAT,
ft_percent FLOAT,
orb_per_100_poss FLOAT,
drb_per_100_poss FLOAT,
trb_per_100_poss FLOAT,
ast_per_100_poss FLOAT,
stl_per_100_poss FLOAT,
blk_per_100_poss FLOAT,
tov_per_100_poss FLOAT,
pf_per_100_poss FLOAT,
pts_per_100_poss FLOAT
);

CREATE TABLE IF NOT EXISTS team_stats_per_game (
season INT,
lg VARCHAR(10),
team VARCHAR(50),
abbreviation VARCHAR(3),
playoffs TINYINT,
g FLOAT,
mp_per_game FLOAT,
fg_per_game FLOAT,
fga_per_game FLOAT,
fg_percent FLOAT,
x3p_per_game FLOAT,
x3pa_per_game FLOAT,
x3p_percent FLOAT,
x2p_per_game FLOAT,
x2pa_per_game FLOAT,
x2p_percent FLOAT,
ft_per_game FLOAT,
fta_per_game FLOAT,
ft_percent FLOAT,
orb_per_game FLOAT,
drb_per_game FLOAT,
trb_per_game FLOAT,
ast_per_game FLOAT,
stl_per_game FLOAT,
blk_per_game FLOAT,
tov_per_game FLOAT,
pf_per_game FLOAT,
pts_per_game FLOAT
);

CREATE TABLE IF NOT EXISTS team_summaries (
season INT,
lg VARCHAR(10),
team VARCHAR(50),
abbreviation VARCHAR(3),
playoffs TINYINT,
age FLOAT,
w FLOAT,
l FLOAT,
pw FLOAT,
pl FLOAT,
mov FLOAT,
sos FLOAT,
srs FLOAT,
o_rtg FLOAT,
d_rtg FLOAT,
n_rtg FLOAT,
pace FLOAT,
f_tr FLOAT,
x3p_ar FLOAT,
ts_percent FLOAT,
e_fg_percent FLOAT,
tov_percent FLOAT,
orb_percent FLOAT,
ft_fga FLOAT,
opp_e_fg_percent FLOAT,
opp_tov_percent FLOAT,
opp_drb_percent FLOAT,
opp_ft_fga FLOAT,
arena VARCHAR(255),
attend FLOAT,
attend_g FLOAT
);

CREATE TABLE IF NOT EXISTS team_totals (
season INT,
lg VARCHAR(10),
team VARCHAR(50),
abbreviation VARCHAR(3),
playoffs TINYINT,
g FLOAT,
mp FLOAT,
fg FLOAT,
fga FLOAT,
fg_percent FLOAT,
x3p FLOAT,
x3pa FLOAT,
x3p_percent FLOAT,
x2p FLOAT,
x2pa FLOAT,
x2p_percent FLOAT,
ft FLOAT,
fta FLOAT,
ft_percent FLOAT,
orb FLOAT,
drb FLOAT,
trb FLOAT,
ast FLOAT,
stl FLOAT,
blk FLOAT,
tov FLOAT,
pf FLOAT,
pts FLOAT
);

/*
CREATE TABLE IF NOT EXISTS define_team_stats (
team VARCHAR(255),
abbreviation VARCHAR(255),
starting_season INT(4),
final_season INT(4),
made_playoffs INT(3)
);
*/
